services:
  document-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: document-service-docker
    restart: always
    container_name: document-service-api
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - BUILD_CONFIGURATION=Release
