services:
  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379

  osmodoc:
    build:
      context: .
      dockerfile: Dockerfile
    image: osmodoc-docker
    container_name: osmodoc-api
    env_file:
      - .env
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_ENVIRONMENT=Development
      - BUILD_CONFIGURATION=Release
